#######################################################################################
# Book settings
title : Text-to-Image Generation
author: PseudoLab
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  Paper/code review and experimental findings related to Text-to-Image Generation models

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/pseudo-lab/text-to-image-generation
  path_to_book                : "book"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
